version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  lint_and_unit_test:
    executor:
      name: node/default
      tag: '18.0.0'
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Lint affected projects
          command: npx nx affected:lint --base=HEAD~1 --head=HEAD
      - run:
          name: Run unit tests for affected projects
          command: npx nx affected:test --base=HEAD~1 --head=HEAD --testPathIgnorePatterns=mongoUrlStorage.test.ts,providerContract.test.ts

  mongodb_integration_test:
    docker:
      - image: cimg/node:18.0.0
      - image: mongo:6.0
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run test
          command: npx nx test server --testFile=tests/mongoUrlStorage.test.ts

  contract_test:
    executor:
      name: node/default
      tag: '18.0.0'
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run contract test
          command: npx nx test server --testFile=tests/providerContract.test.ts

  server_e2e_test:
    docker:
      - image: cimg/node:18.0.0
      - image: mongo:6.0
    environment:
      PORT: 80
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Start server
          command: npx nx run server:serve:production
          environment:
            MONGODB_URI: mongodb://localhost:27017
            MONGODB_DATABASE_NAME: url-shortener
            SERVER_DOMAIN: sh.rt
            CLIENT_ORIGIN: https://client-origin-for-cors.com
          background: true
      - run:
          name: Wait for server to start
          command: sleep 15
      - run:
          name: Run e2e test
          command: npx nx run server-e2e:e2e

workflows:
  build_and_test:
    jobs:
      - lint_and_unit_test
      - mongodb_integration_test:
          requires:
            - lint_and_unit_test
      - contract_test:
          requires:
            - lint_and_unit_test
      - server_e2e_test:
          requires:
            - lint_and_unit_test
