version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  lint_and_unit_test:
    executor:
      name: node/default
      tag: '18.0.0'
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Lint affected projects
          command: npx nx affected:lint --base=HEAD~1 --head=HEAD
      - run:
          name: Run unit tests for affected projects
          command: npx nx affected:test --base=HEAD~1 --head=HEAD --testPathIgnorePatterns=mongoUrlStorage.test.ts,providerContract.test.ts

  mongodb_integration_test:
    docker:
      - image: circleci/node:12.10
      - image: circleci/mongo:4.2.0
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run test
          command: npx nx test server --testFile=tests/mongoUrlStorage.test.ts

workflows:
  build_and_test:
    jobs:
      - lint_and_unit_test
      - mongodb_integration_test
          requires:
            - lint_and_unit_test
